language: python
sudo: false
cache: pip

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - "TRAVIS_SPEEDUP_OPTS=--with-speedups"
  - "TRAVIS_SPEEDUP_OPTS=--without-speedups"

addons:
  apt:
    packages:
      - libgeos-dev
      - python-numpy

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install unittest2; fi
  - pip install pip setuptools --upgrade
  - pip install --install-option="--no-cython-compile" cython

install:
  - pip install -e .[test]
  - pip install coveralls

script: "py.test --cov shapely --cov-report term-missing ${TRAVIS_SPEEDUP_OPTS}"

after_success:
  - coveralls || echo "!! intermittent coveralls failure"
  - bash -x travis-docs.sh
  
notifications:
    email: false
